# Actividad 2: Practicando las operaciones (Matrices)

En este notebook resolvemos cada operación **indicando si es posible** (por dimensiones) y, si lo es, la realizamos.

> **Reglas rápidas**
- **Suma/resta**: solo si las matrices tienen **el mismo tamaño**.
- **Multiplicación**: si la primera es \(m\times n\) y la segunda \(n\times p\), entonces sí se puede y el resultado es \(m\times p\).
- **Escalar**: se multiplica **cada entrada** por el número.


In [14]:
import numpy as np
from fractions import Fraction


def show(A):
    """Imprime una matriz/array de forma más legible."""
    return np.array(A, dtype=object)


## 1) Suma de matrices

$$
\begin{pmatrix}
3 & -2 & 5\\
0 & 4 & 1
\end{pmatrix}
+
\begin{pmatrix}
-1 & 6 & 0\\
7 & -3 & 2
\end{pmatrix}
$$

✅ **Sí se puede** porque ambas son matrices **2×3**. Se suma **posición por posición**.

In [15]:
A1 = np.array([[3, -2, 5],
               [0,  4, 1]])
B1 = np.array([[-1,  6, 0],
               [ 7, -3, 2]])

A1, B1, A1 + B1


(array([[ 3, -2,  5],
        [ 0,  4,  1]]),
 array([[-1,  6,  0],
        [ 7, -3,  2]]),
 array([[2, 4, 5],
        [7, 1, 3]]))

In [16]:
# Implementación manual de la suma
A1_manual = [[3, -2, 5], [0, 4, 1]]
B1_manual = [[-1, 6, 0], [7, -3, 2]]

if len(A1_manual) == len(B1_manual) and len(A1_manual[0]) == len(B1_manual[0]):
    suma_manual = [[A1_manual[i][j] + B1_manual[i][j] for j in range(len(A1_manual[0]))] for i in range(len(A1_manual))]
    print("Suma manual:", suma_manual)
else:
    print("No se puede sumar")

Suma manual: [[2, 4, 5], [7, 1, 3]]


## 2) Multiplicación de matrices

$$
\begin{pmatrix}
2 & -1 & 3\\
0 & 4 & 5
\end{pmatrix}
\cdot
\begin{pmatrix}
1 & 0\\
-2 & 3\\
4 & 1
\end{pmatrix}
$$

✅ **Sí se puede** porque la primera es **2×3** y la segunda es **3×2** (coincide el 3).
El resultado será **2×2**.

In [17]:
A2 = np.array([[2, -1, 3],
               [0,  4, 5]])
B2 = np.array([[ 1, 0],
               [-2, 3],
               [ 4, 1]])

A2.shape, B2.shape, A2 @ B2


((2, 3),
 (3, 2),
 array([[16,  0],
        [12, 17]]))

In [18]:
# Implementación manual de la multiplicación
A2_manual = [[2, -1, 3], [0, 4, 5]]
B2_manual = [[1, 0], [-2, 3], [4, 1]]

if len(A2_manual[0]) == len(B2_manual):
    filas = len(A2_manual)
    columnas = len(B2_manual[0])
    multiplicacion_manual = [[0 for _ in range(columnas)] for _ in range(filas)]
    for i in range(filas):
        for j in range(columnas):
            for k in range(len(B2_manual)):
                multiplicacion_manual[i][j] += A2_manual[i][k] * B2_manual[k][j]
    print("Multiplicación manual:", multiplicacion_manual)
else:
    print("No se puede multiplicar")

Multiplicación manual: [[16, 0], [12, 17]]


## 3) Suma de matrices (¿se puede?)

$$
\begin{pmatrix}
2 & -1 & 4\\
0 & 3 & 5\\
7 & 1 & -2
\end{pmatrix}
+
\begin{pmatrix}
1 & 0\\
-3 & 2\\
4 & -1
\end{pmatrix}
$$

❌ **No se puede** porque las dimensiones no coinciden:
- Primera: **3×3**
- Segunda: **3×2**

Para sumar, deben ser del **mismo tamaño**.

In [19]:
A3 = np.array([[ 2, -1,  4],
               [ 0,  3,  5],
               [ 7,  1, -2]])
B3 = np.array([[ 1,  0],
               [-3,  2],
               [ 4, -1]])

A3.shape, B3.shape


((3, 3), (3, 2))

In [20]:
# Verificación manual para suma
A3_manual = [[2, -1, 4], [0, 3, 5], [7, 1, -2]]
B3_manual = [[1, 0], [-3, 2], [4, -1]]

puede_sumar = len(A3_manual) == len(B3_manual) and len(A3_manual[0]) == len(B3_manual[0])
print("¿Se puede sumar?", puede_sumar)

¿Se puede sumar? False


## 4) Multiplicación por escalar



$$
4\cdot
\begin{pmatrix}
\tfrac12 & -3\\
4 & -\tfrac52
\end{pmatrix}
$$

✅ **Sí se puede**: se multiplica **cada entrada** por 4.

In [21]:
A4 = np.array([[Fraction(1,2), -3],
               [4,            Fraction(-5,2)]], dtype=object)

result4 = 4 * A4
show(A4), show(result4)


(array([[Fraction(1, 2), -3],
        [4, Fraction(-5, 2)]], dtype=object),
 array([[Fraction(2, 1), -12],
        [16, Fraction(-10, 1)]], dtype=object))

In [22]:
# Implementación manual de multiplicación por escalar
A4_manual = [[0.5, -3], [4, -2.5]]
escalar = 4
escalar_manual = [[escalar * A4_manual[i][j] for j in range(len(A4_manual[0]))] for i in range(len(A4_manual))]
print("Escalar manual:", escalar_manual)

Escalar manual: [[2.0, -12], [16, -10.0]]


## 5) Multiplicación por escalar

$$
-3\cdot
\begin{pmatrix}
\tfrac{3}{9} & -\tfrac{11}{6}\\
-7 & 12
\end{pmatrix}
$$

✅ **Sí se puede**: se multiplica **cada entrada** por \(-3\).

In [23]:
A5 = np.array([[Fraction(3,9), Fraction(-11,6)],
               [-7,           12]], dtype=object)

result5 = -3 * A5
show(A5), show(result5)


(array([[Fraction(1, 3), Fraction(-11, 6)],
        [-7, 12]], dtype=object),
 array([[Fraction(-1, 1), Fraction(11, 2)],
        [21, -36]], dtype=object))

In [24]:
# Implementación manual de multiplicación por escalar
A5_manual = [[1/3, -11/6], [-7, 12]]  # 3/9 = 1/3
escalar = -3
escalar_manual = [[escalar * A5_manual[i][j] for j in range(len(A5_manual[0]))] for i in range(len(A5_manual))]
print("Escalar manual:", escalar_manual)

Escalar manual: [[-1.0, 5.5], [21, -36]]


## 6) Multiplicación de matrices (¿se puede?)

$$
\begin{pmatrix}
3 & -1\\
0 & 2\\
5 & 4\\
-2 & 7
\end{pmatrix}
\cdot
\begin{pmatrix}
1 & 0 & 3 & -1\\
2 & 5 & -2 & 4\\
6 & -3 & 1 & 0
\end{pmatrix}
$$

❌ **No se puede** porque:
- Primera: **4×2**
- Segunda: **3×4**

Para multiplicar se requiere que las dimensiones internas coincidan: \(2 = 3\), pero **no coinciden**.

In [25]:
A6 = np.array([[ 3, -1],
               [ 0,  2],
               [ 5,  4],
               [-2,  7]])
B6 = np.array([[ 1,  0,  3, -1],
               [ 2,  5, -2,  4],
               [ 6, -3,  1,  0]])

A6.shape, B6.shape


((4, 2), (3, 4))

In [26]:
# Verificación manual para multiplicación
A6_manual = [[3, -1], [0, 2], [5, 4], [-2, 7]]
B6_manual = [[1, 0, 3, -1], [2, 5, -2, 4], [6, -3, 1, 0]]

puede_multiplicar = len(A6_manual[0]) == len(B6_manual)
print("¿Se puede multiplicar?", puede_multiplicar)

¿Se puede multiplicar? False


---
# Resumen de resultados

1. ✅ \(A_1 + B_1 = \begin{pmatrix}2&4&5\\7&1&3\end{pmatrix}\)
2. ✅ \(A_2B_2 = \begin{pmatrix}16&0\\12&17\end{pmatrix}\)
3. ❌ No se puede (3×3 vs 3×2)
4. ✅ \(4A_4 = \begin{pmatrix}2&-12\\16&-10\end{pmatrix}\)
5. ✅ \(-3A_5 = \begin{pmatrix}-1&\tfrac{11}{2}\\21&-36\end{pmatrix}\)
6. ❌ No se puede (4×2 vs 3×4)
